[project]
name = "vcf-generator-lite"
version = "6.0.1"
description = "A lightweight VCF creation tool written in Python."
authors = [{ name = "Jesse205", email = "jesse205@qq.com" }]
license = "Apache-2.0"
license-files = ["LICENSE"]
readme = "README_pypi.md"
requires-python = ">=3.12"
dependencies = ["ttk-text==0.3.4"]
import-names = ["vcf_generator_lite"]

[project.optional-dependencies]
console = ["colorlog>=6.9.0"]

[dependency-groups]
basic = ["poethepoet>=0.46.0"]
lint = ["pyright>=1.1.411", "ruff>=0.15.13"]
test = ["pytest>=9.0.3"]
build = ["packaging>=26.2", "pyinstaller>=6.20.0", "requests>=2.34.2"]
docs = ["jinja2>=3.1.6", "rumdl>=0.2.40"]
l10n = ["babel>=2.18.0"]
dev = [
    "colorlog>=6.9.0",
    { include-group = "basic" },
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "build" },
    { include-group = "docs" },
    { include-group = "l10n" },
]

[project.urls]
Repository = "https://gitee.com/hellotool/VCFGeneratorLiteWithTkinter"
Github = "https://github.com/hellotool/VCFGeneratorLiteWithTkinter"
Issues = "https://gitee.com/hellotool/VCFGeneratorLiteWithTkinter/issues/new/choose"

[project.gui-scripts]
vcf-generator-lite = "vcf_generator_lite.__main__:main"

[build-system]
requires = ["uv_build>=0.11.3,<0.12"]
build-backend = "uv_build"

[tool.poe]
executor = "uv"
include = "poe_tasks.toml"

[tool.uv.build-backend]
source-exclude = ["*.pot", "*.po"]

[tool.babel]

[[tool.babel.mappings]]
encoding = "utf-8"
method = "python"
pattern = "**.py"
keywords = ["pgettext_menu_label:1c,2", "LazyPgettext:1c,2"]
