# $schema: https://json.schemastore.org/ruff.json

line-length = 120
include = [
    "pyproject.toml",
    "src/**/*.py",
    "tests/**/*.py",
    "scripts/**/*.py",
    "packaging/**/*.py",
    "packaging/pyinstaller/*.spec",
]

[lint]
ignore = [
    "D100",    # 有时候文档不是必须的
    "D101",
    "D102",
    "D103",
    "D104",
    "D107",
    "D400",    # 不支持中文标点
    "PLC0415", # 为了防止兼容性问题或者不必要的代码运行，需要将导入放到函数内。
    "FBT001",  # 在设置单个值时不需要命名参数
    "FBT003",
    "ICN001",  # 很多情况下简写语义不明，要尽量避免简写
    "T201",    # 有 CLI 需求
    "PLR0913", # 参数多不是问题，问题是参数多且没使用命名参数
    "PLR2004", # 有时候，一些长度判断、常见状态码不需要常量
    "S113",    # 万一就是要等很长时间
    "ANN003",  # 无法做到
    "ANN201",  # 为了保持简洁，None 类型不写返回类型
    "ANN202",
    "ANN204",
    "COM812",  # 可能与 Formatter 冲突
    "TRY003",  # 没有必要
    "EM101",
    "EM102",
]
select = ["ALL"]
allowed-confusables = ["，", "：", "（", "）", "；"] # 允许中文符号
exclude = ["tests/**"]

[lint.pydocstyle]
convention = "pep257"

[format]
docstring-code-format = true
line-ending = "lf"
