contact_links:
  - name: Submit feedback on Gitee
    url: https://gitee.com/hellotool/VCFGeneratorLiteWithTkinter/issues/new/choose
    about: If you prefer using Gitee, you can also submit feedback there.