# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: Jesse205.VCFGeneratorLite
PackageVersion: 6.0.1.40000
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
