; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "VCF Generator Lite"
#define MyAppPublisher "Jesse205"
#define MyAppExeName "vcf-generator-lite.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2CA151A5-049F-4AD9-92B1-5F0A244F52A4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={cm:MyAppName} {#MyAppVersion}
AppCopyright={#MyAppCopyright}
AppPublisher={cm:MyAppPublisher}
AppPublisherURL={cm:MyAppPublisherURL}
AppReadmeFile={cm:MyAppReadmeFile}
AppUpdatesURL={cm:MyAppUpdatesURL}
DefaultDirName={autopf}\{#MyAppPublisher}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=..\..\LICENSE
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=..\..\dist
OutputBaseFilename={#OutputBaseFilename}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern dynamic
ArchitecturesAllowed={#ArchitecturesAllowed}
ArchitecturesInstallIn64BitMode={#ArchitecturesInstallIn64BitMode}
AllowNoIcons=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
VersionInfoOriginalFileName={#OutputBaseFilename}.exe
VersionInfoVersion={#VersionInfoVersion}
VersionInfoCompany={#MyAppPublisher}
ShowLanguageDialog=auto

[Languages]
Name: en_us; MessagesFile: "compiler:Default.isl"
Name: zh_cn; MessagesFile: ".extensions\Languages\ChineseSimplified.isl"

[CustomMessages]
MyAppName=VCF Generator Lite
en_us.MyAppName=VCF Generator Lite
en_us.MyAppPublisher=Jesse205
en_us.MyAppPublisherURL=https://github.com/Jesse205
en_us.MyAppReadmeFile=https://github.com/hellotool/VCFGeneratorLiteWithTkinter/blob/master/README.md
en_us.MyAppUpdatesURL=https://github.com/hellotool/VCFGeneratorLiteWithTkinter/releases
en_us.OSNotSupportedMessage=The version of Windows you are currently using is too old, and this application cannot run on this system.%n%nWe provide compatibility solutions for older versions of Windows. Please refer to the following guide:%n%nhttps://gitee.com/hellotool/VCFGeneratorLiteWithTkinter/blob/master/docs/troubleshooting/runs-on-older-windows.md
en_us.UninstallFailed=Uninstall failed

zh_cn.MyAppName=VCF 生成器 轻量版
zh_cn.MyAppPublisher=Jesse205
zh_cn.MyAppPublisherURL=https://gitee.com/Jesse205
zh_cn.MyAppReadmeFile=https://gitee.com/hellotool/VCFGeneratorLiteWithTkinter/blob/master/README.md
zh_cn.MyAppUpdatesURL=https://gitee.com/hellotool/VCFGeneratorLiteWithTkinter/releases
zh_cn.OSNotSupportedMessage=您当前使用的 Windows 版本过旧，本应用无法在此系统上运行。%n%n我们提供了针对旧版 Windows 的兼容运行方案，请参阅以下指南：%n%nhttps://gitee.com/hellotool/VCFGeneratorLiteWithTkinter/blob/master/docs/troubleshooting/runs-on-older-windows.md
zh_cn.UninstallFailed=自动卸载失败

[Code]

function GetUninstallString(): String;
var
  UninstallPath: String;
begin
  UninstallPath :=
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\' +
    '{2CA151A5-049F-4AD9-92B1-5F0A244F52A4}_is1';
  if RegQueryStringValue(HKA, UninstallPath, 'UninstallString', Result) then
    Exit;

  Result := '';
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  UninstallCmd: String;
  ResultCode: Integer;
  ErrorMessage: String;
begin
  if (CurStep = ssInstall) then
  begin
    UninstallCmd := GetUninstallString();
    if UninstallCmd <> '' then
    begin
      UninstallCmd := RemoveQuotes(UninstallCmd);
      if FileExists(UninstallCmd) then
      begin
        if not Exec(UninstallCmd, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '',
            SW_HIDE, ewWaitUntilTerminated, ResultCode) then
        begin
          ErrorMessage := CustomMessage('UninstallFailed') + #13#10 +
            SysErrorMessage(ResultCode) + ' (' + IntToStr(ResultCode) + ')';

          MsgBox(ErrorMessage, mbError, MB_OK);
        end;
      end;
    end;
  end;
end;

var
  OSNotSupportedMessageShown: Boolean;

procedure InitializeWizard();
begin
  OSNotSupportedMessageShown := False;
end;

procedure CurInstallProgressChanged(CurProgress, MaxProgress: Integer);
var
  WinVersion: TWindowsVersion;
begin
  GetWindowsVersionEx(WinVersion);
  if (CurProgress=MaxProgress) and (WinVersion.Major = 6) and (WinVersion.Minor = 1) and (not OSNotSupportedMessageShown) then
  begin
    MsgBox(CustomMessage('OSNotSupportedMessage'), mbInformation, MB_OK);
    OSNotSupportedMessageShown := True;
  end;
end;

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\..\dist\vcf_generator_lite\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{cm:MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{cm:MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{cm:MyAppName}}"; Flags: nowait postinstall skipifsilent

