from collections.abc import Iterator
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from scripts.dependencies import BUILD, DEV, DOCS, L10N, OPTIONAL, RUNTIME

PATH_PROJECT = Path(__file__).resolve().parent.parent
PATH_TEMPLATES = PATH_PROJECT / "templates"

OUTPUT_TEMPLATE = """<!-- DO NOT EDIT THIS FILE DIRECTLY.
     This file is auto-generated.
     Template: templates/{template_name}
     Config:   scripts/dependencies.py
-->

{content}
"""


def _get_render_targets() -> Iterator[tuple[str, str]]:
    for template_path in PATH_TEMPLATES.glob("NOTICES.*.j2.md"):
        lang = Path(template_path.stem).stem
        output_name = "NOTICES.md" if lang == "NOTICES.en" else f"{lang}.md"
        yield (template_path.name, output_name)


def render() -> None:
    env = Environment(loader=FileSystemLoader(PATH_TEMPLATES), autoescape=False)  # noqa: S701
    ctx = {
        "runtime": RUNTIME,
        "optional": OPTIONAL,
        "dev": DEV,
        "l10n": L10N,
        "docs": DOCS,
        "build": BUILD,
    }
    for template_name, output_name in _get_render_targets():
        print(f"Rendering {template_name} -> {output_name}")
        template = env.get_template(template_name)
        content = OUTPUT_TEMPLATE.format(template_name=template_name, content=template.render(**ctx).strip())
        (PATH_PROJECT / output_name).write_text(content, encoding="utf-8", newline="\n")
