import re
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path, PurePath

from jinja2 import Environment, FileSystemLoader

from scripts.dependencies import BUILD, DEV, OPTIONAL, RUNTIME

PATH_PROJECT = Path(__file__).resolve().parent.parent
PATH_TEMPLATES = PATH_PROJECT / "templates"

OUTPUT_TEMPLATE = """<!-- DO NOT EDIT THIS FILE DIRECTLY.
     This file is auto-generated from templates/{template_name}.
     Source: scripts/dependencies.py
     Generated: {datetime}
-->

{content}
"""

NOTICE_REGEX = re.compile(r"(NOTICES(?:\.[a-zA-Z-]+)?)\.j2\.md")


def _get_render_targets() -> Iterator[tuple[str, str]]:
    for template_path in PATH_TEMPLATES.glob("NOTICES*.j2.md"):
        lang = PurePath(template_path.stem).stem
        output_name = f"{lang}.md"
        yield (template_path.name, output_name)


def render() -> None:
    env = Environment(loader=FileSystemLoader(PATH_TEMPLATES), autoescape=False)  # noqa: S701
    ctx = {
        "runtime": RUNTIME,
        "optional": OPTIONAL,
        "dev": DEV,
        "build": BUILD,
    }
    for template_name, output_name in _get_render_targets():
        print(f"Rendering {template_name} -> {output_name}")
        template = env.get_template(template_name)
        rendered = template.render(**ctx).strip()
        rendered = NOTICE_REGEX.sub(r"\1.md", rendered)
        content = OUTPUT_TEMPLATE.format(
            template_name=template_name,
            output_name=output_name,
            content=rendered,
            datetime=datetime.now(UTC).isoformat(timespec="seconds"),
        )
        (PATH_PROJECT / output_name).write_text(content, encoding="utf-8", newline="\n")
