name: Build

on:
  workflow_dispatch:
    inputs:
      build-windows-installer:
        description: Build Windows Installer
        type: boolean
        default: true
      build-windows-portable:
        description: Build Windows Portable
        type: boolean
        default: true
      build-python3-zipapp:
        description: Build Python 3 Zip Application
        type: boolean
        default: true
      build-python3-wheel:
        description: Build Python 3 Wheel
        type: boolean
        default: true
  workflow_call:
    inputs:
      build-windows-installer:
        description: Build Windows Installer
        type: boolean
        default: false
      build-windows-portable:
        description: Build Windows Portable
        type: boolean
        default: false
      build-python3-zipapp:
        description: Build Python 3 Zip Application
        type: boolean
        default: false
      build-python3-wheel:
        description: Build Python 3 Wheel
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  # 合并相似的构建以加快速度、节约成本。
  build-windows-installer-and-portable:
    if: ${{ inputs.build-windows-installer || inputs.build-windows-portable }}
    name: Build Windows Installer and Portable
    runs-on: windows-latest
    env:
      UV_NO_DEFAULT_GROUPS: true
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.0.0
      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Build Portable Package
        if: ${{ inputs.build-windows-portable }}
        run: uv run --group build --group basic poe build-portable

      - name: Build Installer
        if: ${{ inputs.build-windows-installer }}
        run: uv run --group build --group basic poe build-installer

      - name: Upload Portable Package
        id: upload-portable
        if: ${{ inputs.build-windows-portable }}
        uses: actions/upload-artifact@v7
        with:
          name: windows-portable
          path: dist/*-portable.zip
          if-no-files-found: error

      - name: Upload Installer
        id: upload-installer
        if: ${{ inputs.build-windows-installer }}
        uses: actions/upload-artifact@v7
        with:
          name: windows-installer
          path: dist/*-setup.exe
          if-no-files-found: error

  build-python3-zipapp-and-wheel:
    if: ${{ inputs.build-python3-zipapp || inputs.build-python3-wheel }}
    name: Build Python 3 ZIP Application and Wheel
    runs-on: ubuntu-latest
    env:
      UV_NO_DEFAULT_GROUPS: true
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.0.0
      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Build Wheel
        if: ${{ inputs.build-python3-wheel }}
        run: uv run --group build --group basic poe build-wheel

      - name: Build Zip Application
        if: ${{ inputs.build-python3-zipapp }}
        run: uv run  --group build --group basic poe build-zipapp

      - name: Upload Wheel
        id: upload-wheel
        if: ${{ inputs.build-python3-wheel }}
        uses: actions/upload-artifact@v7
        with:
          name: python3-wheel
          path: dist/*.whl
          if-no-files-found: error

      - name: Upload Zip Application
        id: upload-zipapp
        if: ${{ inputs.build-python3-zipapp }}
        uses: actions/upload-artifact@v7
        with:
          name: python3-zipapp
          path: dist/*.pyzw
          if-no-files-found: error
